dtbo-$(CONFIG_ARCH_FSL_IMX8MQ) += nd108t-i2c.dtbo \
                                  nd108t-spi.dtbo \
                                  nd108t-uart.dtbo \
                                  nd108t-lvds-tm070jdhg30.dtbo

targets += dtbs dtbs_install
targets += $(dtbo-y)

always      := $(dtbo-y)
clean-files := *.dtbo
